version: "3"

volumes:

  home:

networks:
  default:
    external: true
    name: isam_v9

services:
  ansible:
    hostname: ansible
    container_name: ansible
    image: ubuntu
    environment:
      - TZ=America/New_York
    volumes:
      - home:/home
    command: >
      bash -c "
        echo 'Running apt-get update...';
        apt-get update -y >/dev/null 2>&1;
        echo 'Installing curl...';
        apt-get install -y curl >/dev/null 2>&1;
        echo 'Downloading host_setup.sh...';
        curl $FILESHARE/scripts/ansible/setup_host.sh > /tmp/setup_host.sh;
        cat /tmp/setup_host.sh;
        echo 'Running host_setup.sh...';
        bash /tmp/setup_host.sh;
        echo '*** Setup Complete! ***';
        tail -f /dev/null;"
        
